### ISSUE TITLE
Autcomplete is unresponsive for some genes

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#26]
@kltm can confirm this result

For sample searches, try:

spe-11
pal-1

**Comment by vanaukenk** [comment]
More specific comments on behavior:

Typing spe-11 and space, then back to remove the space, the autocomplete list appears.

**Comment by tmushayahama** [comment]
@kltm @cmungall when I put q:spe-11* in the request it is returning empty results, but q:spe-11 * then there is match. What should be the value of q or do I need something else on the request. The following is the full request

_:1516912159227
callback_type:search
defType:edismax
facet:true
facet.field:source
facet.field:subset
facet.field:regulates_closure_label
facet.field:is_obsolete
facet.limit:25
facet.mincount:1
facet.sort:count
fl:*,score
fq:document_category:"ontology_class"
fq:regulates_closure:"CHEBI:23367"
indent:on
json.nl:arrarr
packet:1
q:spe-11*
qf:annotation_class^3
qf:annotation_class_label_searchable^5.5
qf:description_searchable^1
qf:comment_searchable^0.5
qf:synonym_searchable^1
qf:alternate_id^1
qf:regulates_closure^1
qf:regulates_closure_label_searchable^1
qt:standard
rows:10
start:0
wt:json
json.wrf:angular.callbacks._b

**Comment by kltm** [comment]
@tmushayahama Without digging in too much, this is likely due to the code using it's own query builder from the fields, rather than the library we have for this (a design decision from the predecessor's development). I suspect that is has to do with the lack of quotes around the query and the `-` being treated as a control character. If so, it may be informative to look at the how the manager software does the escaping in the graph editor or other autocompletes.

**Comment by vanaukenk** [comment]
Hi,
This autocomplete issue is still a problem for C. elegans genes.
If we type, for example:
lin-
we get a list of genes without having to backspace, but only ten genes appear and since there are many lin- genes, we may not get the one we are looking for.
If we type the full gene name, for example:
lin-29
then we have to type a space, and then backspace, in order to get the correct entry in the autocomplete list.

**Comment by vanaukenk** [comment]
There are also issues with the autocomplete for other entities, e.g. anatomy terms.
If I type:
'forelimb'
in the part_of Anatomy box for CC
with no space, I get a list of terms that begins with
'forelimb zeugopod skeleton'.
If I then type a space, nothing changes, but if I type a space and then backspace, the UBERON term for forelimb appears at the top of the list, which is the term I was originally hoping to find.

**Comment by vanaukenk** [comment]
@tmushayahama - will the autocomplete issue wrt C. elegans gene names be resolved when your working copy is merged into Noctua-dev?
The autocomplete for C. elegans genes works fine on the graphical interface on Noctua and Noctua-dev.  Thx.

**Comment by vanaukenk** [comment]
@tmushayahama - it looks like the autocomplete is still not working optimally for C. elegans gene names in the SAE on Noctua-dev.
Would you have time this week to look at this with me so we can get this working?  
As a reference, all is fine on the graphical interface.  Thx.

**Comment by tmushayahama** [comment]
@vanaukenk now working. Special characters are now treated as text. Also worked on the autocomplete various unresponsiveness issues including pasting of values (https://github.com/geneontology/simple-annoton-editor/issues/25) and trimming whitespaces values.
However, @kltm I have opened this issue (https://github.com/geneontology/simple-annoton-editor/issues/50)  so that I can using the manager query builder
