### ISSUE TITLE
Add a NOT button to each aspect

### ISSUE THREAD

**Issue by cmungall** [geneontology/simple-annoton-editor#3]
Required for 
https://github.com/geneontology/noctua/issues/524

**Comment by kltm** [comment]
The main technical discussion occurred here:

 https://github.com/geneontology/noctua/issues/218

Note that we proceeded with the "weaker" example in the right (the
second code example).

For how this plays out in code, you may be interested in the
`issue-218-graph` branch in noctua:

 https://github.com/geneontology/noctua/tree/issue-218-graph

which is currently deployed on noctua-dev.berkeleybop.org.
Specifically, you may be interested in the changes that went into adding
the NOT for one of the input boxes:

 https://github.com/geneontology/noctua/commit/3f9b1fbeb77e5fade447e1ed778c16920e781eba#diff-8c16ba9653dceb85fc3380c81f23061c

**Comment by tmushayahama** [comment]
I am able to create the complement. However, I cannot read the id and label as they are null (picture below). What is the way to get the id/label data? 
![image](https://user-images.githubusercontent.com/2273929/35125145-64475b10-fc5d-11e7-8081-31bc4c313718.png)

**Comment by kltm** [comment]
There is no "class id" for a complement--it is merely the complement of whatever class expressions is wraps.
That said, you probably want to look at the use of the class expression library around complements:
https://github.com/berkeleybop/class-expression/blob/master/tests/core.tests.js#L215
As well (and I assume that it is debugging code above, but I'll be pedantic :), you'd probably want to strictly use the class-expressions API, rather than probe the objects on your own.

**Comment by tmushayahama** [comment]
Let me know what you think about this approach and if it the correct behavior with this new editor. with extensions. On each aspect, there is a toggle "Complement" button as shown in the following picture. The parent aspect is the only node to be complemented not its children and does not traverse down the children. 
As an example, if you complement MF to ![MF], it does **not** complement HasInput and HappensDuring
![image](https://user-images.githubusercontent.com/2273929/35372158-4cf4ffb8-014d-11e8-91cd-bc9837910e9f.png)

**Comment by kltm** [comment]
The complement applies to only the class expression of a single individual (not annoton or aspect). Visually, what you have done appears to be a `not` on three different individual, rather than just one. It may be better to model this as a checkbox of some kind and a clear visual cue once it has been checked.

Tagging @cmungall as well.

**Comment by cmungall** [comment]
Let's keep it simple. Negation should be forbidden if the user specifies any nested values for F/P/C. The chance for user logic error is high and there is no real use case for this.

**Comment by tmushayahama** [comment]
The logic is 

Case 1 - The user negates then all the nested values of that section is disabled
![image](https://user-images.githubusercontent.com/2273929/36834438-c68059e4-1ce7-11e8-80f0-d3c76815ca6e.png)

Case 2 - If the user has already put values on the nested, then the user will not be allowed to negate
![image](https://user-images.githubusercontent.com/2273929/36834502-ec09a864-1ce7-11e8-93ae-c30e573ed126.png)

Solved in
https://github.com/geneontology/simple-annoton-editor/commit/bf4fd4616f5ba9bc508f99f3f12cdf8a35518d86
