### ISSUE TITLE
easier way? for curators to enter annoton without a function

### ISSUE THREAD

**Issue by krchristie** [geneontology/simple-annoton-editor#46]
I was thinking that it might be simpler and _more_ intuitive for curators if there was just a checkbox in the MF section to indicate "no MF to enter" rather than having those options hidden in the menu on the side. 

In addition, right now, the other options are:
- Default
- CC only
- BP only

But what about this kind of case, where I have BP terms, CC terms, a cell type, and an anatomy term, but no MF:

![bpncc-womf-annoton](https://user-images.githubusercontent.com/10533218/38047843-84de6002-3278-11e8-81de-3ffbf5f439f9.jpg)

If you feel the need to keep this in a dropdown menu, then how about only two options:
- with MF (or "known MF", but "default" isn't a very informative name)
- no MF

**Comment by vanaukenk** [comment]
I agree that 'Default' is not very informative for curators, but I think there's more happening with the different forms than just MF or no MF and wonder if there's a succinct way to capture that with the different names for the forms.

How about something like this:
MF, BP, CC (enables, involved in, occurs in)
BP (other causal relation)
CC (part of)

However, this makes me wonder if we should actually have this:
MF, BP, CC (enables, involved in, occurs in)
MF, BP, CC (enables, other causal relation, occurs in)
CC (part of)

and include an MF and CC in what is now the BP only form.

We might also then display all the relations on the forms, just like we are currently doing for the BP only.

I am open to suggestions for how we might do this better, but overall, the goal is to try to make it clearer on the SAE what relations and statements are being made while curators are entering their annotations so that when they look at the resulting annotations in the graphical interface what they see matches the statements they intended to make.

**Comment by krchristie** [comment]
One thing that I'm trying to get at is that right now is that there isn't a template that allows BP _AND_ CC without entering MF. So, I think that a BP+CC (aka no MF) template would be easier and more useful than having the two individual templates for BP only and CC only. Since the current BP only template only allows 1 BP at a time, it is not useful for the scenario in the screenshot above where I have 2 BP terms, 1 CC term, 1 CL term, and 1 anatomy term. 

Considering that switching from one template to another can lose info that was entered (see https://github.com/geneontology/simple-annoton-editor/issues/49), I think that it might be easiest for curators if you can change the relationships on the info you have entered, rather than having to have a template for every variation. While the BP only template allows choice of other relationships, it doesn't let me connect this to CC info, and it is really common for me to have a couple BP terms where the anonymous MF is "upstream of" rather than "part of" the BP AND where I have CC info, or at least cell type and anatomy, so if I have to enter these BPs one at a time in the SAE, then I still have to enter most of the info separately and connect it in the graph.

I think it might be simplest if the default form of the SAE is like it is now, but let you change the relationships of the MF to the BP terms, though it would be really nice if this was something more like a pull down that fit into the space where the text "Part Of (BP)" is now, instead of taking up a whole row like it does in the BP ONLY template. It might also simplify things if on this same template, you could tick a box to indicate "no MF to enter" or whatever text is preferred, rather than having to change to a new template, especially if you've already entered things.
