### ISSUE TITLE
Add a clone or "template" button to the operations

### ISSUE THREAD

**Issue by kltm** [geneontology/simple-annoton-editor#5]
A common curator use case is to base their next annotation on a past one.

This feature would be almost identical to the current edit button actions, except that there is no destructive step.

**Comment by tmushayahama** [comment]
@kltm @thomaspd @cmungall are we doing this for 1.0.

**Comment by thomaspd** [comment]
@vanaukenk do you think this is a feature we should try to add at this point?

**Comment by vanaukenk** [comment]
@thomaspd - this is definitely a feature curators have asked for (see #17)
Thinking through how this would work in practice - if a curator cloned a version of the data entered into the table, they'd get a new tab (?) with a view of the duplicated annotation in the editor that they could edit and then save to their model.  
Perhaps the clone option could also be available from within each box of molecular activities at the bottom of the editor, alongside the Delete option?

**Comment by thomaspd** [comment]
@vanaukenk  - thanks, as Sabrina suggested, this sounds like something to add as an option from the "activity" boxes on the bottom.  It would be cleanest to make a new item "Clone" under the "..." button.  Pressing that button would populate all the fields from that activity into the form.  Would that work?

**Comment by vanaukenk** [comment]
@thomaspd - yes, I think that would work.  Thx.

**Comment by tmushayahama** [comment]
How to Clone/Prepopulate

Below are the 2 methods to clone, I would say "populating the form". Since you cannot edit the model once created, the values are just prepopulated on the form and a user has to manually save it
@pgaudet @thomaspd @vanaukenk @suzialeksander @krchristie let me know if both methods are intuitive and also to give the functionality a proper verb, clone, populate, fill

**Method 1 - Cloning From Model**

Step 1 - Select an existing model and click clone
![image](https://user-images.githubusercontent.com/2273929/38116285-473df9aa-3364-11e8-928e-b4342d98a3e2.png)

Step 2 - The Form will be prepopulated, you can adjust to your needs then click save
![image](https://user-images.githubusercontent.com/2273929/38116363-9509cfce-3364-11e8-8147-112f73ebb296.png)

**Method 2 - Create From Existing**
This one is kinda natural as it is top down and flows well

Step 1- Select Create From Existing
![image](https://user-images.githubusercontent.com/2273929/38116401-c15481aa-3364-11e8-89a6-34ed926523df.png)

Step 2 - Select All or choose which field(s)
![image](https://user-images.githubusercontent.com/2273929/38116908-19e42c74-3367-11e8-999d-64b630fb46bf.png)


Step 3 - It will fill the form with those fields then click save
![image](https://user-images.githubusercontent.com/2273929/38116510-3a21c638-3365-11e8-96c1-57cafbb222b7.png)
