### ISSUE TITLE
Display user group parenthetically like the graph editor

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#56]
The graph editor displays the selected user group parenthetically to the right of the user name.

This is a good reminder to curators as to what group they are currently annotating for.

Can the display of groups be made the same in the SAE?

Thx.

**Comment by tmushayahama** [comment]
@vanaukenk 

I can put it there, but originally it was put here (pic below) as it showed it was affecting only the form being currently created and not the table view of already created models.
![image](https://user-images.githubusercontent.com/2273929/38825571-e62b7e6a-4161-11e8-8360-ad3f1d048609.png)
Let me know what you think. I can put on both or remove it on the form..

**Comment by vanaukenk** [comment]
Thanks @tmushayahama 
Maybe having it on both would be best.  I like the visual cue next to the curator name, but I don't think we need to also take it off the form.

**Comment by krchristie** [comment]
The SAE also needs to recognize when a user has more than one group in the YAML file. I have two groups, "MGI" and "GO Central". In the graph editor, you can see both when I click on my groups with tick boxes to change the selection. 
![20180417-graphgrouppulldown](https://user-images.githubusercontent.com/10533218/38893064-110726e8-423e-11e8-8bf3-e365309416ed.jpg)

However, in the SAE, when I click on the pull down, I only have one group.
![20180417-saegrouppulldown](https://user-images.githubusercontent.com/10533218/38893074-19689ef2-423e-11e8-9a0e-4944fdf2a42d.jpg)

I also like how the Graph group pull down menu still shows my existing info instead of covering it up. Is that possible in the SAE?

Here's a model I created, though I don't know if you'll see my groups when you are logged in: 
http://68.181.125.145:8910/workbench/simple-annoton-editor/?model_id=gomodel:5a7e68a100000324
