### ISSUE TITLE
The NOT qualifier does not seem to appear

### ISSUE THREAD

**Issue by kltm** [geneontology/simple-annoton-editor#95]
From @krchristie 

**1. In the form editor**

The NOT qualifier does not seem to appear at all in the form view. There are two annotations to the term 'phasphatidylinositol-4,5-bisphosphate binding' in this model, one without a NOT and one WITH a NOT. However, in the form view you cannot tell the which one has the NOT qualifier. The one that is supposed to have it is the row highlighted in gray; compare to the top row.

![20190530-noNOTinForm](https://user-images.githubusercontent.com/10533218/58671759-941dec00-82f8-11e9-87a7-378ab02092e4.jpg)

Similarly to the Annotation Preview, it would be fine to place the qualifier right next to the 'enabled by' relationship. However, for readability in the curation interface, it would be preferable if it was displayed as <NOT enabled by> rather than <enabled by|NOT> like it does in the Annotation preview.

**Comment by krchristie** [comment]
Looks like I left out a phrase in my comment above and I can't edit the above since it was done by @kltm instead of me.

Similarly to the Annotation Preview, it would be fine to place the qualifier right next to the 'enabled by' relationship. However, for readability in the curation interface, it would be preferable if it was displayed as something like "**NOT enabled by**" rather than **<enabled by|NOT>** like it does in the Annotation preview.

**Comment by tmushayahama** [comment]
@krchristie Yes, a little hiccup, I always forget that GP and MF are reversed. I will revise this, but is it ok if I just put it in the new Noctua Form

@vanaukenk @krchristie just to clarify. There is no NOT on the extensions?

**Comment by vanaukenk** [comment]
@tmushayahama 

> There is no NOT on the extensions?

That is correct; there is no NOT on the extensions.  The only place the NOT value is used is to negate the GO term in the primary (i.e. unextended) annotation.
